name: Run Build Test

on: [push, pull_request]

jobs:
  run-build-test:      
    name: Run Build Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
              npm install
              npm run build
